services:
    #fields
    juice_upload.juice_upload_image_field:
        class: Juice\UploadBundle\Form\ImageType
        tags:
            - { name: form.type, alias: juice_upload_image_field }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload.juice_upload_file_field:
        class: Juice\UploadBundle\Form\FileType
        tags:
            - { name: form.type, alias: juice_upload_file_field }

    juice_upload.juice_upload_gallery_field:
        class: Juice\UploadBundle\Form\GalleryType
        tags:
            - { name: form.type, alias: juice_upload_gallery_field }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload.juice_upload_gallery_child_field:
            class: Juice\UploadBundle\Form\GalleryItemType
            tags:
                - { name: form.type, alias: juice_upload_gallery_child_field }

    #types
    juice_upload.juice_upload_image_type:
        class: Juice\UploadBundle\Form\Type\BaseImageType
        tags:
            - { name: form.type, alias: juice_upload_image_type }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload.juice_upload_gallery_item_type:
        class: Juice\UploadBundle\Form\Type\BaseGalleryItemType
        tags:
            - { name: form.type, alias: juice_upload_gallery_item_type }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload.juice_upload_file_type:
        class: Juice\UploadBundle\Form\Type\BaseFileType
        tags:
            - { name: form.type, alias: juice_upload_file_type }

    #others
    juice_upload_bundle.handler.crop:
        class: Juice\UploadBundle\Handler\CropHandler

    juice_upload_bundle.twig.file_extension:
        class: Juice\UploadBundle\Twig\FileExtension
        tags:
            - { name: twig.extension }
        arguments: [ "@liip_imagine.filter.manager" ]




