services:
    #fields
    juice_upload_bundle.juice_single_image_field:
        class: Juice\UploadBundle\Form\ImageType
        tags:
            - { name: form.type, alias: juice_single_image_field }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload_bundle.juice_single_file_field:
        class: Juice\UploadBundle\Form\FileType
        tags:
            - { name: form.type, alias: juice_single_file_field }

    juice_upload_bundle.juice_gallery_field:
        class: Juice\UploadBundle\Form\Type\BaseGalleryType
        tags:
            - { name: form.type, alias: juice_gallery_field }

    juice_upload_bundle.juice_gallery_child_field:
            class: Juice\UploadBundle\Form\GalleryImageType
            tags:
                - { name: form.type, alias: juice_gallery_child_field }

    #types
    juice_upload_bundle.juice_image_type:
        class: Juice\UploadBundle\Form\Type\BaseImageType
        tags:
            - { name: form.type, alias: juice_image_type }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload_bundle.juice_gallery_image_type:
        class: Juice\UploadBundle\Form\Type\BaseGalleryChildType
        tags:
            - { name: form.type, alias: juice_gallery_image_type }
        arguments: [ "@liip_imagine.filter.manager" ]

    juice_upload_bundle.juice_file_type:
        class: Juice\UploadBundle\Form\Type\BaseFileType
        tags:
            - { name: form.type, alias: juice_file_type }

    #others
    juice_upload_bundle.handler.crop:
        class: Juice\UploadBundle\Handler\CropHandler
        arguments: ['@service_container', "@liip_imagine.filter.manager" ]
        scope: request

    juice_upload_bundle.twig.file_extension:
        class: Juice\UploadBundle\Twig\FileExtension
        tags:
            - { name: twig.extension }
        arguments: [ "@liip_imagine.filter.manager" ]




